version: '3'
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-docker
    expose:
      - "5432"
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:latest
    env_file:
      - .env
    expose:
      - "5432"